### ISSUE TITLE
Wrong typing syntax?

### ISSUE THREAD

**Issue by skarnproject** [nutti/fake-bpy-module#29] opened 2020-04-19 16:42 UTC
I looked at the generated fake modules to resolve the issue with some types being deduced incorrectly. It seems the generator tool inserts parentheses into class names of types which represent a container?

Quick example.

does not work:
class Action:
    '''A collection of F-Curves for animation '''

    fcurves: typing.List['FCurve'] = None

works now: 
class Action:
    '''A collection of F-Curves for animation '''

    fcurves: typing.List[FCurve] = None

Is there any specific reason for this?

**Comment by nutti** [comment] 2020-04-20 12:45
@skarnproject 

What python version do you use?
`typing.List['FCurve']` works well in my environment, but `typing.List[FCurve]` does not work.

**Comment by skarnproject** [comment] 2020-04-23 07:08
Python 3.7.4

**Comment by nutti** [comment] 2020-04-23 11:19
@skarnproject 

Thanks.
If you don't mind, I would like to know what editor you used.

**Comment by skarnproject** [comment] 2020-04-23 11:40
PyCharm Professional

**Comment by nutti** [comment] 2020-04-25 09:40
I could not reproduce this issue.
I use PyCharm Community Edition instead of Professional, and works correctly.

<img width="734" alt="github_20200425" src="https://user-images.githubusercontent.com/1463952/80276467-feffbf00-8723-11ea-86b2-1b13877f1c1d.png">

**Comment by nutti** [comment] 2020-05-06 09:00
Sorry, I have not reproduced this issue until now.
I will close this issue for now.
But I will consider this issue again, if there are same issues happen at someone's environment.

**Closed by nutti** 2020-05-06 09:00 UTC
