### ISSUE TITLE
Specific type of bpy_prop_collection is not taken into account

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#204] opened 2024-05-12 09:06 UTC
### Description about the bug

For example:
`bpy.data.actions.new()` is missing because because `bpy.data.actions` has the type `bpy.types.bpy_prop_collection[Action]` instead of `bpy.types.BlendDataActions`.

fake-bpy-module-latest: 20240511

**Comment by nutti** [comment] 2024-05-14 11:44
This issue was automatically solved by solving #205.

**Comment by Road-hog123** [comment] 2024-05-18 14:30
Unfortunately the reported issue does not actually appear to be fixed, or has regressed since this issue was closed—`BlendData.actions` is still `bpy_prop_collection[Action]` when it should be `BlendDataActions`, and is only one of many like it.

**Comment by JonathanPlasse** [comment] 2024-05-18 15:26
Indeed, thank you for catching it.

**Comment by nutti** [comment] 2024-05-19 00:27
@Road-hog123 

Ah, yes. I didn't notice that.
Reopened this issue.

**Comment by nutti** [comment] 2024-05-19 11:10
Fixed now.

**Closed by nutti** 2024-05-19 11:10 UTC
Labels: bug

**Comment by Road-hog123** [comment] 2024-05-19 16:01
Ah, this has fixed the reported issue (`bpy.data.actions.new()` is no longer missing) but caused regressions in other areas... `mesh.vertices[0]` is perceived as `Any` instead of `MeshVertex`; I'm suspecting because `MeshVertices` inherits from both `bpy_struct` and `bpy_prop_collection[MeshVertex]`.

[MeshVertices is documented as inheriting from just `bpy_struct`](https://docs.blender.org/api/current/bpy.types.MeshVertices.html)—this feels like a documentation error, given it clashes with the [definition of `Mesh.vertices`](https://docs.blender.org/api/current/bpy.types.Mesh.html#bpy.types.Mesh.vertices) as a `bpy_prop_collection[MeshVertex]`?

**Comment by nutti** [comment] 2024-05-27 09:40
@Road-hog123 

Is this the same as #234 ?

**Comment by Road-hog123** [comment] 2024-05-27 11:42
I believe it is—after doing some inspection `bpy.data.objects` should not inherit from `bpy_struct` at all.

(the documentation is *technically* correct—`bpy.types.BlendDataObjects` inherits from `bpy_struct`—but `bpy.data.objects` is not an instance of `bpy.types.BlendDataObjects`. I don't know why Blender has to be so awkward)
