### ISSUE TITLE
Issue with ID return type on ID class and Depsgraph

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#270] opened 2024-06-24 13:06 UTC
See example below, since those methods on `ID` and `Depsgraph` are defined with `-> ID`, it always returns `ID` and doesn't consider the actual type. 

![image](https://github.com/nutti/fake-bpy-module/assets/9417531/0c55ad7c-6cf1-446c-8d3f-de6cac4cd274)

To resolve this for `ID` methods using `-> typing.Self` would work.
For `Depsgraph` it would require a `typing.TypeVar` bounded to `ID` in both `Depsgraph.id_eval_get` argument and return types.

```python
import bpy
from typing import assert_type

material = bpy.data.materials["test"]
# "assert_type" mismatch: expected "Material" but received "ID"
assert_type(material.copy(), bpy.types.Material)

obj = bpy.data.objects["Test"]
depsgraph = bpy.context.evaluated_depsgraph_get()

# "assert_type" mismatch: expected "Object" but received "ID"
assert_type(obj.override_create(), bpy.types.Object)
assert_type(obj.override_hierarchy_create(), bpy.types.Object)
assert_type(obj.make_local(), bpy.types.Object)
assert_type(obj.evaluated_get(depsgraph), bpy.types.Object)
assert_type(depsgraph.id_eval_get(obj), bpy.types.Object)
```

**Comment by Road-hog123** [comment] 2024-06-30 05:49
Duplicate of [#161](https://github.com/nutti/fake-bpy-module/issues/161#issuecomment-2118849070).

**Comment by nutti** [comment] 2024-07-20 10:04
This issue is now resolved.

**Closed by nutti** 2024-07-20 10:04 UTC
Labels: bug
