### ISSUE TITLE
Default value `sys.float_info.max` converted to `None`

### ISSUE THREAD

**Issue by Road-hog123** [nutti/fake-bpy-module#284] opened 2024-07-09 18:36 UTC
[`BVHTree.ray_cast`](https://docs.blender.org/api/current/mathutils.bvhtree.html#mathutils.bvhtree.BVHTree.ray_cast)'s `distance` argument defaults to `sys.float_info.max`, but in the generated modules this has become `None` (which is not compatible with `float`).

**Comment by Road-hog123** [comment] 2024-07-21 22:43
[`bpy.utils.resource_path`](https://docs.blender.org/api/main/bpy.utils.html#bpy.utils.resource_path) has a similar problem—`major` defaults to `bpy.app.version[0]` and `minor` to `bpy.app.version[1]`, but in the generated modules these are `None[0]` and `None[1]` respectively (`None` is not subscriptable).

**Comment by nutti** [comment] 2024-08-01 09:39
Duplicate of #267.
Solved by fixing it.

**Closed by nutti** 2024-08-01 09:39 UTC
Labels: duplicate
