### ISSUE TITLE
There is no data file in the bpy file

### ISSUE THREAD

**Issue by liuhaorandezhanghao** [nutti/fake-bpy-module#87] opened 2021-04-26 08:04 UTC
scene = bpy.data.scenes['Scene']
and error:AttributeError: 'NoneType' object has no attribute 'scenes'

**Comment by nutti** [comment] 2021-04-26 11:01
@liuhaorandezhanghao 

In my environment, I could not reproduce this error.
Could you tell me your environment?

**Comment by liuhaorandezhanghao** [comment] 2021-04-27 03:19
Hi ，the code is :scene = bpy.data.scenes['Scene’]
 But in my environment, there is no profile named data, so how did you install bpy??




On 04/26/2021 ***@***.***> wrote：

@liuhaorandezhanghao

In my environment, I could not reproduce this error.
Could you tell me your environment?

**Comment by nutti** [comment] 2021-04-27 09:36
@liuhaorandezhanghao 

Did you follow the [installation int the document](https://github.com/nutti/fake-bpy-module#install-via-pip-package) ?

**Comment by liuhaorandezhanghao** [comment] 2021-04-29 09:32
bpy.data.armatures[0].edit_bones[bone_name_from_index[0]].head
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
KeyError: 'bpy_prop_collection[key]: key "Pelvis" not found'






Hi do you know how to resolve it?


On 04/27/2021 ***@***.***> wrote：

@liuhaorandezhanghao

Did you follow the installation int the document ?

**Comment by nutti** [comment] 2021-04-30 01:37
>  File "<blender_console>", line 1, in <module>

It seems that this is a runtime error not fake-bpy-module.
You should redirect this question to the other sites.

So, I will close this issue.

**Closed by nutti** 2021-04-30 01:37 UTC

**Comment by liuhaorandezhanghao** [comment] 2021-05-08 03:02
Is the bpy module bundled with blender and cannot be installed separately? I can only use bpy in blender, and I will get an error when I use it in my python environment. Do you have any good methods?




On 04/30/2021 ***@***.***> wrote：

File "<blender_console>", line 1, in

It seems that this is a runtime error not fake-bpy-module.
You should redirect this question to the other sites.

So, I will close this issue.

**Comment by nutti** [comment] 2021-05-08 04:38
@liuhaorandezhanghao 

> Is the bpy module bundled with blender and cannot be installed separately?

This project is a **fake** bpy module to autocomplete the Blender API in many editors.
You can not execute the program with this module because fake-bpy-module is not same as the bpy module in Blender.

**Comment by liuhaorandezhanghao** [comment] 2021-05-08 05:06
Can the fake-bpy-module you installed work? When the module I installed executes scene = bpy.data.scenes['Scene'], it prompts me that there is no data module in bpy。
thanks




On 05/8/2021 ***@***.***> wrote：

@liuhaorandezhanghao

Is the bpy module bundled with blender and cannot be installed separately?

This project is a fake bpy module to autocomplete the Blender API in many editors.
You can not execute the program with this module because fake-bpy-module is not same as the bpy module in Blender.

**Comment by liuhaorandezhanghao** [comment] 2021-05-08 05:16
Like this:




On 05/8/2021 ***@***.***> wrote：
Can the fake-bpy-module you installed work? When the module I installed executes scene = bpy.data.scenes['Scene'], it prompts me that there is no data module in bpy。
thanks




On 05/8/2021 ***@***.***> wrote：

@liuhaorandezhanghao

Is the bpy module bundled with blender and cannot be installed separately?

This project is a fake bpy module to autocomplete the Blender API in many editors.
You can not execute the program with this module because fake-bpy-module is not same as the bpy module in Blender.

**Comment by nutti** [comment] 2021-05-08 06:56
@liuhaorandezhanghao 

> When the module I installed executes scene = bpy.data.scenes['Scene'], it prompts me that there is no data module in bpy

This is the correct behavior for fake-bpy-module because the fake module does not affect the Blender's internal data.
fake-bpy-module is just a **fake** module which I have already said.
Please understand the difference between **fake**-bpy-module and real bpy module.

**Comment by liuhaorandezhanghao** [comment] 2021-06-16 09:15
Hello, in my fbx output, the character model is always lying on the ground, that is, it is rotated 90 degrees downwards. Where can I change this code?
Thanks




On 05/8/2021 ***@***.***> wrote：
Like this:




On 05/8/2021 ***@***.***> wrote：
Can the fake-bpy-module you installed work? When the module I installed executes scene = bpy.data.scenes['Scene'], it prompts me that there is no data module in bpy。
thanks




On 05/8/2021 ***@***.***> wrote：

@liuhaorandezhanghao

Is the bpy module bundled with blender and cannot be installed separately?

This project is a fake bpy module to autocomplete the Blender API in many editors.
You can not execute the program with this module because fake-bpy-module is not same as the bpy module in Blender.

**Comment by wang-zm18** [comment] 2022-02-26 09:30
> scene = bpy.data.scenes['Scene']
> and error:AttributeError: 'NoneType' object has no attribute 'scenes'

I also meth the same problem, did you solve it?
