### ISSUE TITLE
Latest module update broke mathutils vector

### ISSUE THREAD

**Issue by Rawalanche** [nutti/fake-bpy-module#323] opened 2024-12-11 13:57 UTC
### System Information

* OS: Windows 11
* Blender version: 4.3
* Python 3.12.8
* VSCode PyLint v2024.0.0

### Expected behavior

No linter errors

### Description about the bug

I have updated the module after a while to get autosuggestion for recent features, but the update broke mathutils vector class.

### Screenshots/Files [Optional]

![image](https://github.com/user-attachments/assets/f8494571-faf8-4097-a30a-b759c6eec581)

### Additional comments [Optional]

Older version did not have this problem

**Comment by Andrej730** [comment] 2024-12-13 08:56
@Rawalanche Hi! Can you please provide a concise example how to reproduce the issue? Couldn't reproduce it.

```python
from mathutils import Vector

v = Vector()
v.x += 25
v.y += 25
v.z += 25
```

![image](https://github.com/user-attachments/assets/e52733d5-e6b1-4e45-8517-666dadc5fa1d)

**Comment by Rawalanche** [comment] 2024-12-13 09:07
> @Rawalanche Hi! Can you please provide a concise example how to reproduce the issue? Couldn't reproduce it.
> 
> ```python
> from mathutils import Vector
> 
> v = Vector()
> v.x += 25
> v.y += 25
> v.z += 25
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/9417531/395496157-74fb35ae-030d-4752-b62e-ab569b4a9b93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwODA3ODEsIm5iZiI6MTczNDA4MDQ4MSwicGF0aCI6Ii85NDE3NTMxLzM5NTQ5NjE1Ny03NGZiMzVhZS0wMzBkLTQ3NTItYjYyZS1hYjU2OWI0YTliOTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMDkwMTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzU5MjhlYzk5YjdhYTU3MjdiMjYzNDQ1YmExNWRiYTY1ZjVlMjFiMTA2ZTg3MzI4Y2UwM2U2Yjk5NDRiZDI5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.7xKMVfGCNbP1Hf4xKNR0heYqZ5bEaPs0BO9TC6RDq00)

Hi, yes.
This is the blender addon: https://drive.google.com/file/d/1t15v_IlJAprM5QrU4LhrMCu1XRst7Y3r/view?usp=sharing
And this is packaged virtual environment I use when writing the addon: https://drive.google.com/file/d/1t11Tb1m19JCh-ZdeeSbUf_gpEujN5JYi/view?usp=sharing

The addon has also .vscode folder included which contains settings.json to match exactly my workspace VSCode settings. So to reproduce:
1. Unzip the lk_simplecut and open it as a VSCode workspace
2. Set virtual environment location to the unzipped venv location
3. Activate virtual environment

As long as you have latest VSCode and latest Pylint extension, you should have the same conditions as me.

**Comment by Andrej730** [comment] 2024-12-13 09:33
Is there some more consise way to reproduce it with some snippet?

**Comment by Rawalanche** [comment] 2024-12-13 09:38
> Is there some more consise way to reproduce it with some snippet?

Yes, under those conditions I described above, even your small snippet throws the errors:
![image](https://github.com/user-attachments/assets/eeddcfef-736b-4a94-8c04-0c6b927e1d3e)
But you need to meet those conditions:
1. Windows 11
2. Latest VSCode
3. Latest Pylint extension
4. My workspace: Python 3.12.8 virtual environment with fake-bpy-module 20241211 and my .vscode/settings.json configured to your local venv interpreter path

Those are the conditions under which it happens

**Comment by Andrej730** [comment] 2024-12-13 09:44
Oh, sorry, I've missed the Pylint, thought it's Pylance complaining.
Was able to reproduce it by just enabing Pyling in VS Code, no other special pre-requirements.

**Comment by nutti** [comment] 2024-12-28 09:30
@Rawalanche @Andrej730 

I could not get the root cause of this issue.
Should we fix this from fake-bpy-module side?
It seems that this issue comes from the editor side.

**Comment by Andrej730** [comment] 2024-12-28 11:00
Tried to reproduce this too and couldn't narrow it down too and I don't see any issues with the stub file that can be related. 
I think it's worth to report it to https://github.com/pylint-dev/pylint @Rawalanche

**Comment by nutti** [comment] 2024-12-29 08:55
Thank you @Andrej730 for your confirmation.
I will close this issue for now because this issue should be solved by the other project.

**Closed by nutti** 2024-12-29 08:55 UTC
Labels: invalid
