### ISSUE TITLE
Use most recent Python Syntax in .pyi files

### ISSUE THREAD

**Issue by JonathanPlasse** [nutti/fake-bpy-module#161] opened 2023-12-17 17:40 UTC
In .pyi files, the most recent syntax of python can be used, as it is only used for static analysis.

Therefore, these changes can be made:
- [x] Remove all quotes (future annotation)
- [x] Use `|` instead of `Optional` and `Union` (PEP 604) (#207)
- [x] Use `type` Parameter Syntax (PEP 695)
- [x] Use `list`, `dict`, … instead of `typing.List`, `typing.Dict`, … (PEP 585)
  - [x] builtin (#207)
  - [x] `collections.abc` (#223)
- [x] Use `Self` (PEP 673)
- [x] Add Ruff and enable linter rules to avoid regression we encountered (c.f. #222, #224, #296)

I could work on this, to familiarize myself with the codebase.

**Comment by nutti** [comment] 2024-05-12 12:04
@JonathanPlasse 

Yes, go ahead.
Currently, we use Python 3.9 for the generation which does not support these syntax.
You many need to change Python version as well.
https://github.com/nutti/fake-bpy-module/blob/97f5da91c52f9cab440e16c60cdd1eed5b68329e/.github/workflows/fake-bpy-module-ci.yml#L69

**Comment by JonathanPlasse** [comment] 2024-05-12 12:14
Ok, I will start working on it.

**Comment by nutti** [comment] 2024-05-16 12:41
@JonathanPlasse 

#207 is merged now.
Will you also tackle the remain (PEP695) as wall?

**Comment by JonathanPlasse** [comment] 2024-05-16 13:05
I will.

**Comment by Road-hog123** [comment] 2024-05-18 14:57
Can I suggest [PEP 673](https://peps.python.org/pep-0673/)'s `Self` type as a related change?

Presently `ID.evaluated_get()` returns `ID`, but if this were changed to `Self` then I believe `Object.evaluated_get()` would correctly return `Object` instead of `ID`.

Unfortunately the [documentation](https://docs.blender.org/api/current/bpy.types.ID.html#bpy.types.ID.evaluated_get) just lists the return type as `ID`, so I don't know if there's anything for the generation code to detect to make this change automatically.

**Comment by JonathanPlasse** [comment] 2024-05-19 17:56
To avoid regression, we should use the plugin `flake-pyi` available in Ruff to check we use the modern syntax in the generated code.

**Comment by nutti** [comment] 2024-06-07 11:33
@JonathanPlasse 

Should this issue be still opened?
I think some features have already merged.

**Comment by JonathanPlasse** [comment] 2024-06-07 11:42
> Can I suggest [PEP 673](https://peps.python.org/pep-0673/)'s `Self` type as a related change?
> 
> Presently `ID.evaluated_get()` returns `ID`, but if this were changed to `Self` then I believe `Object.evaluated_get()` would correctly return `Object` instead of `ID`.
> 
> Unfortunately the [documentation](https://docs.blender.org/api/current/bpy.types.ID.html#bpy.types.ID.evaluated_get) just lists the return type as `ID`, so I don't know if there's anything for the generation code to detect to make this change automatically.

This one would be interesting.

> To avoid regression, we should use the plugin `flake-pyi` available in Ruff to check we use the modern syntax in the generated code.

This one would be cool to have.

Is it a problem for you if the issue remains open?
Should we open a specific issue for each remaining point instead?

**Comment by nutti** [comment] 2024-06-07 11:51
No, I just would like to know the current status and the future plan.
We welcome your contribution.

**Comment by JonathanPlasse** [comment] 2024-06-07 12:00
I updated the initial comment.

**Comment by nutti** [comment] 2024-07-07 01:36
@JonathanPlasse 

Ruff linter is now merged to the master branch.
You can tackle the remaining task now.

**Comment by nutti** [comment] 2024-07-20 10:05
@JonathanPlasse 

> Can I suggest [PEP 673](https://peps.python.org/pep-0673/)'s `Self` type as a related change?
> 
> Presently `ID.evaluated_get()` returns `ID`, but if this were changed to `Self` then I believe `Object.evaluated_get()` would correctly return `Object` instead of `ID`.
> 
> Unfortunately the [documentation](https://docs.blender.org/api/current/bpy.types.ID.html#bpy.types.ID.evaluated_get) just lists the return type as `ID`, so I don't know if there's anything for the generation code to detect to make this change automatically.

By solving this feature, I solved below item.
* Use Self (PEP 673)

**Comment by nutti** [comment] 2024-07-20 10:07
@JonathanPlasse 

I think below item seems to have already been resolved by the ruff linter introduced.

* Add Ruff and enable linter rules to avoid regression we encountered

How do you think about it?

**Comment by JonathanPlasse** [comment] 2024-07-20 10:51
Does it check that the generated code passes the rules of flake8-pyi?

**Comment by nutti** [comment] 2024-09-23 06:37
> Use type Parameter Syntax

This is introduced by https://github.com/nutti/fake-bpy-module/commit/d08d5c4100d3c896b08a03db70cf529766f5104c.

**Comment by nutti** [comment] 2024-09-23 06:37
Close this issue because all tasks are done.

**Closed by nutti** 2024-09-23 06:37 UTC
Labels: enhancement
